const data = [
  {
    id: 1,
    title: "men's sneaker",
    description: 'Best for outing',
    price: 20,
    discount: 5,
    category: "Men's fitness",
    image: 'https://res.cloudinary.com/kingsleyibe-net/image/upload/v1662298356/shoppingcartReactApp/pexels-web-donut-19090_lk8g8y.jpg',
    inStock: true,
    color: 'blue',
  },
  {
    id: 2,
    title: "men's sneaker",
    description: 'Best for outing',
    price: 20,
    discount: 5,
    category: "Men's fitness",
    image: 'https://res.cloudinary.com/kingsleyibe-net/image/upload/v1662298357/shoppingcartReactApp/pexels-dom-j-45982_mtx0xw.jpg',
    inStock: true,
    color: 'blue',
  },
  {
    id: 3,
    title: "men's sneaker",
    description: 'Best for outing',
    price: 20,
    discount: 5,
    category: "Men's fitness",
    image: 'https://res.cloudinary.com/kingsleyibe-net/image/upload/v1662298358/shoppingcartReactApp/pexels-mnz-1598508_isdglb.jpg',
    inStock: true,
    color: 'blue',
  },
  {
    id: 4,
    title: "men's sneaker",
    description: 'Best for outing',
    price: 20,
    discount: 5,
    category: "Men's fitness",
    image: 'https://res.cloudinary.com/kingsleyibe-net/image/upload/v1662298359/shoppingcartReactApp/pexels-terje-sollie-298863_qjsioe.jpg',
    inStock: true,
    color: 'blue',
  },
  {
    id: 5,
    title: "men's sneaker",
    description: 'Best for outing',
    price: 20,
    discount: 5,
    category: "Men's fitness",
    image: 'https://res.cloudinary.com/kingsleyibe-net/image/upload/v1662298365/shoppingcartReactApp/pexels-mnz-1598505_qobfqk.jpg',
    inStock: true,
    color: 'blue',
  },
];

module.exports = data;
