const data = [
  {
    id: 1,
    title: "men's sneaker",
    description: 'Best for outing',
    price: 20,
    discount: 5,
    category: "Men's fitness",
    image: 'https://www.pexels.com/photo/gray-and-black-striped-crew-neck-top-45982/',
    inStock: true,
    color: 'blue',
  },
  {
    id: 2,
    title: "men's sneaker",
    description: 'Best for outing',
    price: 20,
    discount: 5,
    category: "Men's fitness",
    image: 'https://www.pexels.com/photo/gray-and-black-striped-crew-neck-top-45982/',
    inStock: true,
    color: 'blue',
  },
  {
    id: 3,
    title: "men's sneaker",
    description: 'Best for outing',
    price: 20,
    discount: 5,
    category: "Men's fitness",
    image: 'https://www.pexels.com/photo/gray-and-black-striped-crew-neck-top-45982/',
    inStock: true,
    color: 'blue',
  },
  {
    id: 4,
    title: "men's sneaker",
    description: 'Best for outing',
    price: 20,
    discount: 5,
    category: "Men's fitness",
    image: 'https://www.pexels.com/photo/gray-and-black-striped-crew-neck-top-45982/',
    inStock: true,
    color: 'blue',
  },
  {
    id: 5,
    title: "men's sneaker",
    description: 'Best for outing',
    price: 20,
    discount: 5,
    category: "Men's fitness",
    image: 'https://www.pexels.com/photo/gray-and-black-striped-crew-neck-top-45982/',
    inStock: true,
    color: 'blue',
  },
];

export default data;
